[tool.poetry]
name = "hm-m-poetry"
version = "0.1.0"
description = ""
authors = ["Lenovo <bogdannerushev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
